import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
// import Footer from '@/components/Footer';
// import Silk from '@/components/Silk';
// import Animate from '@/components/AnimatePage';
// import PageTransition from '@/components/PageTransition';

const outFit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="scrollbar-hide">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const theme = localStorage.theme;
                  const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                  if (theme === 'dark' || (!theme && prefersDark)) {
                    document.documentElement.classList.add('dark');
                  }
                } catch (_) {}
              })();
            `,
          }}
        />
      </head>

      <body
        className={`${outFit.className} scrollbar-hide size-full overflow-x-hidden bg-gray-300 from-gray-950 to-gray-700 text-gray-800 antialiased transition-all dark:bg-gradient-to-r dark:text-gray-200`}
      >
        <Header />
        <div className="flex min-h-screen flex-col">
          <main className="grow overflow-x-hidden">{children}</main>
        </div>
      </body>
    </html>
  );
}
// import type { Metadata } from 'next';
// import { Outfit } from 'next/font/google';
// import './globals.css';
// import Header from '@/components/Header';
// import Footer from '@/components/Footer';

// const outFit = Outfit({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={` ${outFit.className} antialiased`}>
//         <Header />
//         <main>{children}</main>
//         <Footer />
//       </body>
//     </html>
//   );
// }
