import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { ThemeProvider } from '@/components/ThemeProvider';
import ThemeScript from '@/components/ThemeScript';

const outFit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth sm:scroll-auto">
      <head>
        <ThemeScript />
      </head>
      <body
        className={`${outFit.className} bg-gray-300 text-gray-800 antialiased transition-all duration-500 dark:bg-gray-900 dark:text-gray-200 dark:duration-500`}
      >
        <ThemeProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
// import type { Metadata } from 'next';
// import { Outfit } from 'next/font/google';
// import './globals.css';
// import Header from '@/components/Header';
// import Footer from '@/components/Footer';

// const outFit = Outfit({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={` ${outFit.className} antialiased`}>
//         <Header />
//         <main>{children}</main>
//         <Footer />
//       </body>
//     </html>
//   );
// }
